### ISSUE TITLE
Receiving support? 

### ISSUE THREAD

**Issue by Francolpm** [desandro/arpeggiator#2]
Hi there! This isn't a issue but I didn't know where to ask!
Are you accepting donations or supports? Because may you get some extra support for arpeggiator, but there is no donate button o something like that.
I don't trying to spam you, but I want to invite you to beerpay.io, a simple platform to monetize open source projects, like arpeggiator. 
I know that the open source is free, but it's okay if someone want to contribute in other way, I'm just saying!

Thanks for this work man!

**Comment by desandro** [comment]
Thanks a lot! Best way to support development is to purchase a license for [Metafizzy](https://metafizzy.co) plugin
